/**
 * TOROGOZ — DATA STORE
 * ---------------------------------------------------------------------
 * Small helper shared by the site pages and the admin page.
 *
 * - Defaults ship in js/data.js as window.TOROGOZ_DATA.
 * - The admin page (admin.html) edits a working copy that lives in this
 *   browser's localStorage, so changes preview instantly on this device.
 * - "Download Updated Data File" in the admin page turns that working
 *   copy into a new js/data.js you upload to your host to publish.
 * ---------------------------------------------------------------------
 */
(function () {
  const STORAGE_KEY = "torogozData";

  function clone(obj) {
    return JSON.parse(JSON.stringify(obj));
  }

  function loadData() {
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw) return JSON.parse(raw);
    } catch (e) {
      console.warn("Could not read locally-edited data, using published defaults.", e);
    }
    return clone(window.TOROGOZ_DATA);
  }

  function saveData(data) {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  }

  function hasLocalEdits() {
    return window.localStorage.getItem(STORAGE_KEY) !== null;
  }

  function resetToPublished() {
    window.localStorage.removeItem(STORAGE_KEY);
  }

  function nextId(list) {
    return (list || []).reduce((max, x) => Math.max(max, x.id || 0), 0) + 1;
  }

  function generateDataFileSource(data) {
    const json = JSON.stringify(data, null, 2);
    return (
      "/**\n" +
      " * TOROGOZ — SITE DATA\n" +
      " * Generated by the admin dashboard on " + new Date().toString() + "\n" +
      " * Upload this file to your web host as js/data.js to publish these changes.\n" +
      " */\n\n" +
      "window.TOROGOZ_DATA = " + json + ";\n"
    );
  }

  window.TorogozStore = {
    STORAGE_KEY,
    loadData,
    saveData,
    hasLocalEdits,
    resetToPublished,
    nextId,
    generateDataFileSource,
    clone
  };
})();
